return {
  "mrjones2014/smart-splits.nvim",
  enabled = (os.getenv("TERM_PROGRAM") == "WezTerm"),
  keys = {
    {
      "n",
      "<A-h>",
      function()
        require("smart-splits").resize_left()
      end,
    },
    {
      "n",
      "<A-l>",
      function()
        require("smart-splits").resize_right()
      end,
    },
    {
      "n",
      "<A-k>",
      function()
        require("smart-splits").resize_up()
      end,
    },
    {
      "n",
      "<A-j>",
      function()
        require("smart-splits").resize_down()
      end,
    },
    {
      "n",
      "<C-h>",
      function()
        require("smart-splits").move_cursor_left()
      end,
    },
    {
      "n",
      "<C-l>",
      function()
        require("smart-splits").move_cursor_right()
      end,
    },
    {
      "n",
      "<C-k>",
      function()
        require("smart-splits").move_cursor_up()
      end,
    },
    {
      "n",
      "<C-j>",
      function()
        require("smart-splits").move_cursor_down()
      end,
    },
  },
}
